name: Terraform

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.5.7
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./soluciones/workload"
          
      - name: 'Terraform plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.5.7
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./soluciones/workload"
        
